disabled = false
languageCode = "fr"
languageName = "Français"
weight = 1
title = "Léon Fievet - Portfolio"

[params]
displayName = "FR"
isoCode = "fr"
rtl = false
dateFormat = "2 January 2006"
# logo = "img/logo.png"
# secondaryLogo = "img/secondary-logo.png"
description = "Portfolio professionnel de Léon Fievet - Développeur Web"
# copyright = "Copy, _right?_ :thinking_face:"

[params.author]
name = "Léon Fievet"
email = "fievet.leon@free.fr"
image = "img/profile.jpg"
headline = "Étudiant en informatique & Développeur Full-Stack"
bio = "Développeur polyvalent passionné par les technologies modernes. De la création d'applications web aux systèmes embarqués, en passant par les microservices en Go et la programmation système en Rust, je combine expertise technique et créativité pour résoudre des problèmes complexes. Pilote et constructeur de drones FPV, j'applique cette même rigueur technique à tous mes projets de développement."
links = [
    { email = "mailto:fievet.leon@free.fr" },
    { email = "mailto:leon.fievet@etu.umontpellier.fr" },
    { linkedin = "https://www.linkedin.com/in/l%C3%A9on-fievet/" },
    { github = "https://github.com/pixnop" }
]