disabled = false
languageCode = "en"
languageName = "English"
weight = 2
title = "Léon Fievet - Portfolio"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "January 2, 2006"
# logo = "img/logo.png"
# secondaryLogo = "img/secondary-logo.png"
description = "Léon Fievet's Professional Portfolio - Web Developer"
# copyright = "Copy, _right?_ :thinking_face:"

[params.author]
name = "Léon Fievet"
email = "fievet.leon@free.fr"
image = "img/profile.jpg"
headline = "Computer Science Student & Web Developer"
bio = "Passionate developer specialized in creating innovative web applications. I combine technical expertise with creative problem-solving to deliver high-performing digital solutions. As an FPV drone pilot and builder, I apply the precision and first-person immersive perspective from this technology to my development work."
links = [
    { email = "mailto:fievet.leon@free.fr" },
    { email = "mailto:leon.fievet@etu.umontpellier.fr" },
    { linkedin = "https://www.linkedin.com/in/l%C3%A9on-fievet/" },
    { github = "https://github.com/pixnop" }
]
