disabled = false
languageCode = "fr"
languageName = "Français"
weight = 1
title = "Léon Fievet - Portfolio"

[params]
displayName = "FR"
isoCode = "fr"
rtl = false
dateFormat = "2 January 2006"
# logo = "img/logo.png"
# secondaryLogo = "img/secondary-logo.png"
description = "Portfolio professionnel de Léon Fievet - Développeur Web"
# copyright = "Copy, _right?_ :thinking_face:"

[params.author]
name = "Léon Fievet"
email = "fievet.leon@free.fr"
image = "img/profile.jpg"
headline = "Étudiant en informatique & Développeur Web"
bio = "Développeur passionné, spécialisé dans la création d'applications web innovantes. Je combine mon expertise technique avec une approche créative pour résoudre des problèmes complexes. Pilote et constructeur de drones FPV, j'applique cette passion pour la technologie aérienne immersive à mon travail de développement."
links = [
    { email = "mailto:fievet.leon@free.fr" },
    { email = "mailto:leon.fievet@etu.umontpellier.fr" },
    { linkedin = "https://linkedin.com/in/leonfievet" },
    { github = "https://github.com/pixnop" }
]