[[main]]
name = "Home"
pageRef = "/"
weight = 10

[[main]]
name = "Journey"
weight = 20

[[main]]
name = "About"
pageRef = "apropos"
weight = 21
parent = "Journey"

[[main]]
name = "Experience"
pageRef = "experience"
weight = 22
parent = "Journey"

[[main]]
name = "Education"
pageRef = "formation"
weight = 23
parent = "Journey"

[[main]]
name = "Skills"
pageRef = "competences"
weight = 24
parent = "Journey"

[[main]]
name = "Learning Portfolio"
pageRef = "portfolio-apprentissage"
weight = 30

[[main]]
name = "Projects"
pageRef = "projets"
weight = 40

[[main]]
name = "Categories"
pageRef = "categories"
weight = 41
parent = "Projects"

[[main]]
name = "Technologies"
pageRef = "tags"
weight = 42
parent = "Projects"

[[main]]
name = "Series"
pageRef = "series"
weight = 43
parent = "Projects"

[[main]]
name = "Contact"
pageRef = "contact"
weight = 50

[[footer]]
name = "LinkedIn"
url = "https://linkedin.com/in/leonfievet"
weight = 10

[[footer]]
name = "GitHub"
url = "https://github.com/pixnop"
weight = 20