[[main]]
name = "Accueil"
pageRef = "/"
weight = 10

[[main]]
name = "Parcours"
weight = 20

[[main]]
name = "À propos"
pageRef = "apropos"
weight = 21
parent = "Parcours"

[[main]]
name = "Expérience"
pageRef = "experience"
weight = 22
parent = "Parcours"

[[main]]
name = "Formation"
pageRef = "formation"
weight = 23
parent = "Parcours"

[[main]]
name = "Compétences"
pageRef = "competences"
weight = 24
parent = "Parcours"

[[main]]
name = "Portfolio d'Apprentissage"
pageRef = "portfolio-apprentissage"
weight = 30

[[main]]
name = "Projets"
pageRef = "projets"
weight = 40

[[main]]
name = "Catégories"
pageRef = "categories"
weight = 41
parent = "Projets"

[[main]]
name = "Technologies"
pageRef = "tags"
weight = 42
parent = "Projets"

[[main]]
name = "Séries"
pageRef = "series"
weight = 43
parent = "Projets"

[[main]]
name = "Contact"
pageRef = "contact"
weight = 50

[[footer]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/l%C3%A9on-fievet/"
weight = 10

[[footer]]
name = "GitHub"
url = "https://github.com/pixnop"
weight = 20